version: "3"
services:
  api:
    container_name: nft-tool-api
    ports:
      - 5000:5000
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./:/app
